# Generated by Django 6.0.3 on 2026-03-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created_at'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['created_at'], 'verbose_name': 'Email Verification'},
        ),
    ]
