# Generated by Django 6.0.3 on 2026-03-24 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='admin_user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'provider_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
